### ISSUE TITLE
Fonts Issue

### ISSUE THREAD

**Issue by RunawaySheld123** [muddasheep/hqtrilogy#231]
When I Open The Game The Fonts Not Working

**Comment by muddasheep** [comment]
Hi RunawaySheld123! Can you post a screenshot? Which language is your primary language?

Does the regular Half-Life work for you, and do other mods work for you as well (such as Headcrab Frenzy or Half-Life C.A.G.E.D)? If yes, I can probably copy some missing files to the HQTrilogy project folder and publish it.

Thanks for reporting!

**Comment by RunawaySheld123** [comment]
![bandicam 2018-12-08 07-31-35-011](https://user-images.githubusercontent.com/26026554/49677741-56fc3e00-fabb-11e8-9e72-6e7a45ef62cd.jpg)

**Comment by muddasheep** [comment]
Ah, thanks a lot for the screenshot! It's actually supposed to look like this, so there's nothing to worry about. (:
