### ISSUE TITLE
main menu

### ISSUE THREAD

**Issue by xzs32** [muddasheep/hqtrilogy#269]
The main menu looks like a bunch of ascii art and has no buttons to click on, because of this i cannot play the mod.

**Comment by muddasheep** [comment]
![image](https://github.com/muddasheep/hqtrilogy/assets/7433200/7bf1a1da-ab97-43c6-8031-eadda7eabdcb)
You should be able to click on "start dying", "arise again", "checklists" and "exit" 🙂
